app/models/blog.py
from .. import db
from config import BASE_DIR

import json
from datetime import datetime
from sqlalchemy import event, or_


class Post(db.Model):
    __tablename__ = 'blog_posts'
    _id = db.Column('id', db.Integer, primary_key=True)

    #: _type和_main_id一起用来区分日志的类型
    #: if _type == 'article' and not _main_id: 已发布的文章
    #: if _type == 'draft' and not _main_id: 未发布的文章
    #: if _type == 'draft' and _main_id: 已发布的文章的修改稿, 已发布的文章的id为_main_id
    _type = db.Column('type', db.String(16))
    _main_id = db.Column('main_id', db.Integer)

    #: _tile即文章的标题, _link是文章的uri, 对于已发布的文章来说, 二者都必须保证唯一性
    _title = db.Column('title', db.String(128))
    _link = db.Column('link', db.String(128), index=True)

    #: _publish_date在文章第一次发表时设置
    #: _edit_date 在文章草稿发布时设置
    #: 后者会在文章详情页显示,以体现文章内容的时效性, 前者用于文章按时间排名
    _publish_date = db.Column('publish_date', db.DateTime)
    _edit_date = db.Column('edit_date', db.DateTime)

    #: _content即日志内容, _abstract为摘要
    _content = db.Column('content', db.Text)
    _abstract = db.Column('abstract', db.Text)

    #: _commendable是日志可评论状态, False不可评论,也不会显示以前的评论
    #: 可评论状态受博客全局可评论设置影响,结果为 settings.enable_post_comment & post.commendable
    _commendable = db.Column('commendable', db.Boolean, default=True)

    #: _public是日志的对外可见状态, False则只有管理员可见
    _public = db.Column('public', db.Boolean, default=True)

    #: _category存储的是文章所属分类的link,包含分类的集成关系信息
    _category = db.Column('category', db.String(128), index=True)

    #: _tags存储的是文章拥有的标签的字符串, 分割符为: ,
    _tags = db.Column('tags', db.String(128), index=True)

    @property
    def id(self):
        return self._id

    @property
    def title(self):
        return self._title or ''

    @title.setter
    def title(self, title):
        if len(title) > 120:
            raise AttributeError('标题最多120个字符')

        # 不允许两篇article的标题相同
        p = Post.query.filter_by(_title=title).first()
        if p and p.type == 'article' and self.type == 'article':
            if not self.id or self.id != p.id:
                raise AttributeError('标题重复')

        self._title = title
        self._link = title.replace(' ', '_')

    @property
    def link(self):
        return self._link or ''

    @property
    def date(self):
        return self._edit_date or None

    @property
    def publish_date(self):
        return self._publish_date or None

    @property
    def content(self):
        return self._content or ''

    @content.setter
    def content(self, content):
        self._content = content
        # 根据content生成abstract
        self._abstract = content.split('<!--more-->', 1)[0]

    @property
    def abstract(self):
        return self._abstract or ''

    @property
    def category(self):
        if self._category:
            cate = Category.query.filter_by(_link=self._category).first()
            return cate
        return None

    @category.setter
    def category(self, cate):
        if not cate:
            cate = Category.query.get(1)
            if not cate:
                cate = Category(name='默认分类')
                db.session.add(cate)

        old_link = self._category
        new_link = cate.link
        self._category = cate.link
        db.session.add(self)

        old_names = old_link.split('/') if old_link else []
        if old_names:
            old_ancestors = [old_names.pop(0)]
            for name in old_names:
                old_ancestors.append('/'.join([old_ancestors[-1], name]))
        else:
            old_ancestors = []

        new_names = new_link.split('/') if new_link else []
        if new_names:
            new_ancestors = [new_names.pop(0)]
            for name in new_names:
                new_ancestors.append('/'.join([new_ancestors[-1], name]))
        else:
            new_ancestors = []

        del_ancestors = [x for x in old_ancestors if x not in new_ancestors]
        for link in del_ancestors:
            ancestor = Category.query.filter_by(_link=link).first()
            if ancestor:
                ancestor.refresh_posts_count()

        for link in new_ancestors:
            ancestor = Category.query.filter_by(_link=link).first()
            if ancestor:
                ancestor.refresh_posts_count()

    @property
    def tags(self):
        return self._tags.split(',') if self._tags else []

    @tags.setter
    def tags(self, tags):
        if not tags:
            tags = ''
        old_tags = self._tags.split(',') if self._tags else []
        new_tags = [tag.strip().lower() for tag in tags.split(',') if tag != '']
        del_tags = [x for x in old_tags if x not in new_tags]

        self._tags = ','.join(new_tags)
        db.session.add(self)

        for tag in new_tags:
            t = Tag.query.filter_by(_name=tag).first()
            if t is None:
                t = Tag(name=tag)
                db.session.add(t)
            t.refresh_posts_count()
        for tag in del_tags:
            t = Tag.query.filter_by(_name=tag).first()
            t.refresh_posts_count()

    @property
    def draft(self):
        return Post.query.filter(Post._main_id == self._id).first() or None

    @property
    def main(self):
        if self._main_id:
            return Post.query.get(self._main_id)
        else:
            return None

    @property
    def type(self):
        return self._type

    @property
    def public(self):
        return self._public

    @public.setter
    def public(self, value):
        if value in [1, '1', 'True', 'public', 'open', True]:
            self._public = True
        else:
            self._public = False
        self.category.refresh_posts_count()
        for tag in self.tags:
            t = Tag.query.filter_by(_name=tag).first()
            t.refresh_posts_count()

    @property
    def commendable(self):
        return self._commendable

    @commendable.setter
    def commendable(self, value):
        if value in [1, '1', 'True', 'commendable', 'on', True]:
            self._commendable = True
        else:
            self._commendable = False

    def add_tag(self, tag):
        if self._tags:
            self._tags = self._tags + ',' + tag.name if tag.name not in self.tags else self._tags
        else:
            self._tags = tag.name
        tag.refresh_posts_count()

    def del_tag(self, delete_tag, refresh_posts_count=True):
        tags = self.tags
        new_tags = [tag for tag in tags if tag != delete_tag.name]
        self._tags = ','.join(new_tags)
        if refresh_posts_count:
            delete_tag.refresh_posts_count()

    @staticmethod
    def publish(post, **data):
        """ 如果post为修改稿, 先
                找到main post,
                更新main post内容, main_post.date = utcnow(),
                再删除post
        """
        if post.type == 'draft' and post._main_id:
            main = post.main
            db.session.delete(post)
            post = main
        db.session.add(post)
        post._type = 'article'
        post.title = data.get('title', '')
        post.content = data.get('content', '')
        post.category = data.get('category', None)
        post.tags = data.get('tags', None)
        post.commendable = data.get('commendable', True)
        post.public = data.get('public', True)
        post._edit_date = datetime.utcnow().replace(microsecond=0)
        post._publish_date = post._publish_date or post._edit_date
        db.session.commit()

    @staticmethod
    def save(post, **data):
        """ 如果post为已发布, 新建edit_post为修改稿, edit_post内容为当前内容,
                                                  edit_post._main_id = post.id
        """
        if post.type == 'article':
            old_draft = post.draft
            if old_draft:
                db.session.delete(old_draft)
            draft = Post()
            draft._main_id = post.id
            post = draft

        post._type = 'draft'
        post.title = data.get('title')
        post.content = data.get('content')
        post.category = data.get('category')
        post.tags = data.get('tags')
        post.commendable = data.get('commendable')
        post.public = data.get('public')
        post._edit_date = datetime.utcnow().replace(microsecond=0)

        db.session.add(post)
        db.session.commit()

    @staticmethod
    def generate_fake(count=30):
        from random import randint
        import forgery_py

        for i in range(count):
            t1 = Tag.query.all()[randint(1, 20)].name
            t2 = Tag.query.all()[randint(1, 20)].name
            t3 = Tag.query.all()[randint(1, 20)].name
            c = Category.query.all()[randint(1, 10)]
            p = Post()
            Post.publish(post=p,
                         title=forgery_py.lorem_ipsum.sentence()[0:110] + str(randint(1, 100)),
                         content=forgery_py.lorem_ipsum.sentences(randint(5, 20)),
                         tags=','.join([t1, t2, t3]),
                         category=c)

    @staticmethod
    def export_json(target_dir=None, export_directly=True):
        if not target_dir:
            target_dir = BASE_DIR
        columns = Post.__table__.columns
        posts = Post.query.all()
        posts_data = [{
                          column.key: getattr(post, '_' + column.key) \
                              if not isinstance(getattr(post, '_' + column.key), datetime) \
                              else str(getattr(post, '_' + column.key).replace(microsecond=0)) for column in columns
                          }
                      for post in posts]
        if export_directly:
            with open('%s/posts.json' % target_dir, 'w') as j:
                json.dump(posts_data, j)
        return posts_data

    def __repr__(self):
        if self._main_id:
            return "[修改稿]: %s" % self._title
        elif self._type == 'draft':
            return "[起草中]: %s" % self._title
        return "[发布稿]: %s" % self._title


class Category(db.Model):
    __tablename__ = 'blog_categories'
    _id = db.Column('id', db.Integer, primary_key=True)

app/forms/blog.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField, SubmitField, SelectField, IntegerField
from wtforms.validators import DataRequired, Length, ValidationError
from ..models import Category, Post


class PostForm(Form):
    title = StringField('标题', validators=[DataRequired(), Length(1, 64, message='标题过长')])
    content = TextAreaField('正文', validators=[DataRequired()])
    tags = StringField('标签')
    publicity = SelectField("对外公开", choices=[(1, "所有人可见"), (0, "仅自己可见")], coerce=int)
    commendable = SelectField("允许评论", choices=[(1, "允许评论"), (0, "禁止评论")], coerce=int)
    publish = SubmitField('发布')
    post_id = IntegerField('id')
    save = SubmitField('保存')

    def validate_title(self, field):
        post = Post.query.filter_by(_title=field.data).first()
        if post and post.id != self.post_id.data and post.type == 'article':
            raise ValidationError('文章标题重复')


class CategoryForm(Form):
    name = StringField('分类名称', validators=[DataRequired(), Length(2, 12, message='分类名称长度在2-12之间')])
    order = IntegerField('排序', default=0)
    cate_id = IntegerField('id')
    submit = SubmitField('提交')

    def validate_name(self, field):
        name = field.data
        if '/' in name:
            raise ValidationError('分类名中不能包含“/”')
        else:
            cate = Category.query.filter_by(_name=name).first()
            if cate and cate.id != self.cate_id.data:
                raise ValidationError('分类已经存在')

app/views/blog.py
from flask import Blueprint, request, render_template, current_app, abort
from flask_login import current_user
from sqlalchemy import or_
from ..models import Post, Category, Tag

blog = Blueprint('blog', __name__)


@blog.route('/index')
@blog.route('/')
def index():
    title = '博客'
    base_query = Post.query.filter_by(_type="article")
    base_query = base_query.filter_by(_public=True) if not current_user.is_administrator else base_query
    query = base_query.order_by(Post._publish_date.desc())

    if query.count() <= current_app.config['POSTS_PER_PAGE']:
        posts = query.all()
        pagination = None
    else:
        page = request.args.get('page', 1, type=int)
        pagination = query.paginate(
            page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False
        )
        posts = pagination.items
    return render_template('blog/index.html',
                           title=title,
                           posts=posts,
                           pagination=pagination)


@blog.route('/post/<path:post_link>')
@blog.route('/category/<path:post_category_link>')
@blog.route('/tag/<path:post_tag_link>')
@blog.route('/archive/<path:post_date_link>')
def post(post_link=None, post_category_link=None, post_tag_link=None, post_date_link=None):
    not_found = True
    if post_link:
        p = Post.query.filter_by(_link=post_link).first()
        if p:
            not_found = False
    elif post_category_link:
        *category_link, post_link = post_category_link.split('/')
        category_link = '/'.join(category_link)
        p = Post.query.filter_by(_link=post_link).first()
        if p and category_link == p._category:
            not_found = False
    elif post_tag_link:
        *tag_link, post_link = post_tag_link.split('/')
        tag_link = '/'.join(tag_link)
        p = Post.query.filter_by(_link=post_link).first()
        if p and tag_link in [t.replace(' ', '_') for t in p.tags]:
            not_found = False
    elif post_date_link:
        *date, post_link = post_date_link.split('/')
        p = Post.query.filter_by(_link=post_link).first()
        if p and '/'.join(date) == '%s/%s' % (p.publish_date.year, p.publish_date.month):
            not_found = False

    if not_found:
        abort(404)

    if not p.public and not current_user.is_authenticated:
        abort(404)

    return render_template('blog/single.html',
                           title=p.title,
                           posts=[p])


@blog.route('/categories')
def categories():
    cates = Category.query.filter_by(_level=0).filter(Category._posts_count != 0).order_by(Category._order).all()
    return render_template('blog/categories.html',
                           categories=cates,
                           title='分类',
                           cates=cates)


@blog.route('/categories/<path:category_link>')
def category(category_link):
    cate = Category.query.filter_by(_link=category_link).first()
    if not cate:
        abort(404)
    children = cate.children.all()
    base_query = Post.query.filter_by(_type="article").filter(or_(Post._category.like(category_link),
                                                                  Post._category.like(category_link + '/%')))
    base_query = base_query.filter_by(_public=True) if not current_user.is_administrator else base_query
    query = base_query.order_by(Post._publish_date.desc())
    if query.count() <= current_app.config['POSTS_PER_PAGE']:
        ps = query.all()
        pagination = None
    else:
        page = request.args.get('page', 1, type=int)
        pagination = query.paginate(
            page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
        ps = pagination.items
    cates = Category.query.filter_by(_level=0).filter(Category._posts_count != 0).order_by(Category._order).all()
    return render_template('blog/category.html',
                           category=cate,
                           categories=children,
                           posts=ps,
                           pagination=pagination,
                           title='分类:' + cate.name,
                           cates=cates)


@blog.route('/tags')
def tags():
    ts = Tag.query.filter(Tag._posts_count != 0).order_by(Tag._posts_count.desc()).all()
    return render_template('blog/tags.html',
                           tags=ts,
                           title='标签')


@blog.route('/tags/<path:tag_link>')
def tag(tag_link):
    t = Tag.query.filter_by(_link=tag_link).first()
    if not t:
        abort(404)
    base_query = Post.query.filter_by(_type="article").filter(or_(Post._tags.like(tag_link + ',%'),
                                                                  Post._tags.like('%,' + tag_link),
                                                                  Post._tags.like(tag_link),
                                                                  Post._tags.like('%,' + tag_link + ',%')))
    base_query = base_query.filter_by(_public=True) if not current_user.is_administrator else base_query
    query = base_query.order_by(Post._publish_date.desc())
    if query.count() <= current_app.config['POSTS_PER_PAGE']:
        ps = query.all()
        pagination = None
    else:
        page = request.args.get('page', 1, type=int)
        pagination = query.paginate(
            page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False
        )
        ps = pagination.items

    tags = Tag.query.filter(Tag._posts_count != 0).order_by(Tag._posts_count.desc()).all()
    return render_template('blog/tag.html',
                           title='标签:' + tag_link,
                           pagination=pagination,
                           posts=ps,
                           tag=t,
                           tags=tags)


@blog.route('/archives')
def archive():
    title = '博客存档'
    ps = Post.query.filter_by(_type='article').order_by(Post._publish_date.desc()).all()
    return render_template('blog/archive.html',
                           posts=ps,
                           title=title,
                           )

app/templates/blog/_base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "blog/_macros.html" as macros %}
{% import "_g_macros.html" as g_macros %}

{% block head %}
    {{ super() }}
    {{ g_macros.render_header("blog") }}
    {% if request.endpoint == 'blog.post' %}
        {% set post = posts[0] %}
        <link rel="canonical"
              href="{{ url_for('blog.post', post_category_link='%s/%s' %(post._category, post.link), _external=True) }}"
        >
    {% endif %}
{% endblock %}

{% block title %}
    {% if title %}{{ title }} - {% endif %}{{ config['SITE_TITLE'] }}
{% endblock %}

{% block navbar %}
    {% include "_g_navbar.html" %}
{% endblock %}

{% block content %}
    <div class="container">
        {% include "_g_flash.html" %}

        <div class="row">
            {% block page_container %}

                <div class="col-md-12">
                    {% block page_main %}

                    {% endblock %}
                </div>

                <div class="col-md-12">
                    <div class="page-footer">
                        <p id="site-description"><i>{{ config['SITE_DESCRIPTION'] }}</i></p>
                    </div>
                </div>


            {% endblock %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap/bootstrap.min.js') }}"></script>
    {{ moment.include_moment(local_js="/static/js/moment-with-locales.min.js") }}

    <script>
        var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
        var $BLOG_CATEGORY_PATH = {{ url_for('blog.categories')|tojson|safe }};
        {% if current_user.is_authenticated %}
            var $CSRF_TOKEN = "{{ csrf_token() }}";
        {% endif %}
        var $READING_BLOG = false
    </script>

    {% if config['DISQUS_IDENTIFIER'] %}
        {% if request.endpoint.startswith('blog.')  or request.endpoint.startswith('main.index') %}
            <script id="dsq-count-scr" src="//{{ config['DISQUS_IDENTIFIER'] }}.disqus.com/count.js" async></script>
        {% endif %}
    {% endif %}

    {% if (request.endpoint in ["blog.index", "blog.post", "blog.tag", "blog.category"]) or
    (current_user.is_anonymous and request.endpoint == "main.index") %}
        <script>$READING_BLOG = true</script>
    {% endif %}

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', '{{ config['GOOGLE_ANALYTICS_CODE'] }}', 'auto');
        ga('send', 'pageview');

    </script>
    <script src="{{ url_for('static', filename='js/blog.js') }}"></script>

{% endblock %}

app/templates/blog/_comments.html
<div id="disqus_thread">

</div>


<script>

    var disqus_config = function () {
        this.page.url = '{{ url_for('blog.post', post_link=posts[0].link, _external=True) }}'; // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = 'post-{{ posts[0].title }}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function () { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');

        s.src = '//{{ config['DISQUS_IDENTIFIER'] }}.disqus.com/embed.js' ;

        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments
    powered by Disqus.</a></noscript>

app/templates/blog/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
    <ul class="pagination">

        <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
            <a href="
        {% if pagination.has_prev %} {{ url_for(endpoint, page=pagination.page - 1, **kwargs) }}
        {% else %}#
        {% endif %}">
                &laquo;
            </a>
        </li>

        {% for p in pagination.iter_pages(3,1,2,3) %}
            {% if p %}
                <li {% if p == pagination.page %} class="active" {% endif %}>
                    <a href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a>
                </li>
            {% else %}
                <li class="disabled">
                    <a href="#">&hellip;</a>
                </li>
            {% endif %}
        {% endfor %}

        <li {% if not pagination.has_next %} class="disabled" {% endif %}>
            <a href="
        {% if pagination.has_next %} {{ url_for(endpoint, page=pagination.page + 1, **kwargs) }}
        {% else %}#
        {% endif %}">
                &raquo;
            </a>
        </li>
    </ul>
{% endmacro %}

{% macro simple_pagination_widget(pagination, endpoint) %}
    <nav>
        <ul class="pager">
            {% if pagination.has_prev %}
                <li class="previous"><a href="{{ url_for(endpoint, page=pagination.page - 1, **kwargs) }}">
                    <span aria-hidden="true">&larr;</span>上一页
                </a></li>
            {% endif %}
            {% if pagination.has_next %}
                <li class="next"><a href="{{ url_for(endpoint, page=pagination.page + 1, **kwargs) }}">
                    下一页<span>&rarr;</span>
                </a></li>
            {% endif %}
        </ul>
    </nav>
{% endmacro %}


{% macro render_post_list(posts, current_user, moment, slug_type=None, slug_value=None, single=False) %}
    <ul class="post-list">
        {% for post in posts %}
            {% if post.public or current_user.is_administrator %}
                <li class="post">
                    <a
                            {% if not single %}
                                {% if not slug_type %}
                                    href="{{ url_for('blog.post', post_link=post.link) }}"
                                {% elif slug_type == 'category' %}
                                    href="{{ url_for('blog.post', post_category_link=slug_value + '/' + post.link) }}"
                                {% elif slug_type == 'tag' %}
                                    href="{{ url_for('blog.post', post_tag_link=slug_value + '/' + post.link) }}"
                                {% endif %}
                            {% endif %}
                    >
                        <h2 class="post-title">{{ post.title }}</h2>
                    </a>

                    <div class="post-meta">
                    <span class="post-date">
                        <span class=" glyphicon glyphicon-calendar" title="日期"></span>&nbsp;
                        {{ moment(post.date).format('LL') }}
                    </span>&nbsp;
                    <span class="post-category">
                        <span class=" glyphicon glyphicon-book" title="分类"></span>&nbsp;
                        <a href="{{ url_for('blog.category', category_link=post._category) }}">
                            {{ post.category.name }}
                        </a>
                    </span>&nbsp;
                        {% if post.tags %}
                            <span class="post-tag">
                        <span class="glyphicon glyphicon-tags" title="标签"></span>&nbsp;
                        {% set tags = post.tags %}
                                {% for tag in tags %}
                                    <a href="{{ url_for('blog.tag', tag_link=tag.replace(' ', '_')) }}">
                                {{ tag }}</a>{% if tag != tags[-1] %},{% endif %}
                                {% endfor %}</span>&nbsp;
                        {% endif %}
                        <span class="post-comment">
                        <span class="glyphicon glyphicon-comment" title="评论"></span>&nbsp;
                        <a href="{{ url_for('blog.post', post_link=post.link, _external=True) }}#disqus_thread"
                           data-disqus-identifier="post-{{ post.title }}">

                        </a>
                    </span>&nbsp;

                        {% if current_user.is_administrator %}
                            <span class="glyphicon glyphicon-pencil"></span>
                            <span class="post-edit">
                        <a href="{{ url_for("admin.edit_post", post_link=post.link, post_version='main') }}">编辑</a></span>
                        {% endif %}
                    </div>

                    <div class="post-content">
                        {% if single or not config['SHOW_ABSTRACT'] %}
                            <div class="content">
                                {{ post.content | markdown | safe }}
                            </div>
                        {% else %}
                            <div class="abstract">
                                {{ post.abstract | markdown | safe }}
                            </div>
                        {% endif %}
                        <span class="read-more">
                            {% if not single %}
                                <a href="{{ url_for('blog.post', post_link=post.link) }}">阅读全文</a>
                            {% endif %}
                            </span>
                    </div>
                </li>
                <hr>
            {% endif %}
        {% endfor %}
    </ul>

{% endmacro %}

app/templates/blog/archive.html
{% extends "blog/_base.html" %}

{% block page_main %}
    <div class="page-main">
        <div class="archive-container">
            <h2 class="cls-section-identifier">存档</h2>
            <hr>
            {% set tmp_year = 0 %}
            {% set start_loop = 0 %}
            {% for post in posts %}
                {% if post.public or current_user.is_authenticated %}
                    {% if post.publish_date.year != tmp_year %}
                        {% set tmp_year = post.publish_date.year %}
                        {% if start_loop == 1 %} </ul>
                        {% else %} {% set start_loop = 1 %}
                        {% endif %}
                        <ul class="{{ post.publish_date.year }}" id="post-archive-list">
                        <h3>{{ tmp_year }}年</h3>
                        <li>{{ post.publish_date.month }}月
                            {% if post.publish_date.day < 10 %}0{% endif %}{{ post.publish_date.day }}日 &raquo; <a
                                    href="{{ url_for("blog.post",
                                                 post_date_link = '%s/%s/%s' % (post.publish_date.year, post.publish_date.month, post.link)) }}">
                                {{ post.title }}</a>
                        </li>
                    {% else %}
                        <li>{{ post.publish_date.month }}月
                            {% if post.publish_date.day < 10 %}0{% endif %}{{ post.publish_date.day }}日 &raquo; <a
                                    href="{{ url_for("blog.post",
                                                 post_date_link = '%s/%s/%s' % (post.publish_date.year, post.publish_date.month, post.link)) }}">
                                {{ post.title }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>

    </div>
{% endblock %}

app/templates/blog/index.html
{% extends "blog/_base.html" %}

{% block page_main %}

    <div class="page-main">

        <div id="post-container">
            {{ macros.render_post_list(posts, moment=moment, current_user=current_user) }}
        </div>

        {% if pagination %}
            <div class="post-pagination">
                {% if request.endpoint == 'main.index' %}
                    {{ macros.simple_pagination_widget(pagination=pagination, endpoint="main.index") }}
                {% else %}
                    {{ macros.simple_pagination_widget(pagination=pagination, endpoint="blog.index") }}
                {% endif %}
            </div>
        {% endif %}

    </div>
{% endblock %}

app/templates/blog/tags.html
{% extends "blog/_base.html" %}

{% block page_main %}
    <div class="page-main">

        <div class="tags-posts-container">

            <div class="cls-tags-show">
                <h2 class="cls-section-identifier">全部标签</h2>
                <hr>
                {% for tag in tags %}
                    <span class="tag-item">
                    <a href="{{ url_for('blog.tag', tag_link=tag.link) }}">
                        {{ tag.name }}</a><sup> {{ tag.posts_count }}</sup>
                    </span>
                {% endfor %}
            </div>

            <div class="cls-tags-posts">
                <h2 class="cls-section-identifier">标签存档</h2>
                <hr>
                {% for tag in tags %}
                    <h3>{{ tag.name }} <sup>{{ tag.posts_count }}</sup></h3>
                    <ul class="cls-tag-posts cls-tag-{{ tag.id }}">
                        {% for post in tag.posts.all()|sort(attribute='publish_date', reverse=True) %}
                            {% if post.public or current_user.is_authenticated %}
                                <li>
                                    <p><a href="{{ url_for('blog.post', post_tag_link=tag.link + '/' + post.link) }}">
                                        {{ moment(post.publish_date).format('LL') }} &raquo;
                                        {{ post.title }}</a></p></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}